# Generated by Django 2.2.3 on 2019-07-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='author',
            new_name='viewer',
        ),
    ]
